### ISSUE TITLE
Dead link in sharing.rst

### ISSUE THREAD

**Issue by Patricol** [freenas/freenas-docs#112]
In [this](https://github.com/freenas/freenas-docs/blob/master/userguide/sharing.rst#unix-nfs-shares) section.

> ... read through the performance analysis at [Running ZFS over NFS as a VMware Store](http://blog.laspina.ca/ubiquitous/running-zfs-over-nfs-as-a-vmware-store).

The page is available [here](https://web.archive.org/web/20171027150737/blog.laspina.ca/ubiquitous/running-zfs-over-nfs-as-a-vmware-store).

**Comment by dlavigne** [comment]
Thanks for the report!

New UI commit: https://github.com/freenas/freenas-docs/commit/c094aa49b1716c93ccebaf4ec9ad74f548ecb2f8

Legacy UI commit: https://github.com/freenas/freenas-docs/commit/40ef44250ec3361cf4f5784d7ac289160089bd4b
