### ISSUE TITLE
SMART acronym not defined in Services section.

### ISSUE THREAD

**Issue by Mrt134** [freenas/freenas-docs#15]
- Tasks -> SMART Tests (http://doc.freenas.org/9.10/tasks.html#s-m-a-r-t-tests): SMART acronym is defined with a link to Wikipedia (https://en.wikipedia.org/wiki/S.M.A.R.T.).
- Services -> S.M.A.R.T. (http://doc.freenas.org/9.10/services.html#s-m-a-r-t): No definition or link to definition.

**Comment by wblock** [comment]
Fixed in a1b51a52088779208bbcd6d93c576da5a4f5e121.
