### ISSUE TITLE
using Ubuntu 16.04, I can't make the pdf

### ISSUE THREAD

**Issue by mr-E** [freenas/freenas-docs#16]
using Ubuntu 16.04, I can't make the pdf
First I try with "make pdf"... then I read the "Makefile" and see that I need to use "pdflatex"
Maybe the main page need to say?:
> To build a PDF:
> make pdflatex

Using "make pdflatex" I got a warning... then an error:

> resolving references...
> writing... /home/.../freenasDoc/freenas-docs/userguide/processed/services.rst:: WARNING: unusable reference target found: he.net
> done
>...
> copying TeX support files...
> done
> build succeeded, 1 warning.
> Running LaTeX files through pdflatex...
>  '# move the table of contents to a different spot
> sed: can't read : No such file or directory
> Makefile:122: recipe for target 'latexpdf' failed
> make: *** [latexpdf] Error 2

Using "make pdf" I got the same error:

> copying TeX support files...
> done
> build succeeded, 1 warning.
> Running LaTeX files through pdflatex...
> '# move the table of contents to a different spot
> sed: can't read : No such file or directory
> Makefile:122: recipe for target 'pdf' failed
> make: *** [pdf] Error 2

**Comment by wblock** [comment]
This sounds like a difference between FreeBSD sed and gsed on Linux.  The first sed line deletes the `\tableofcontents` command, then the second inserts a new one in a different place.  gsed and BSD sed differ somewhat, although I thought they were compatible for this usage.  If you can install BSD sed and verify that it works by modifying those two lines in the Makefile, it would help in diagnosing this.

**Comment by wblock** [comment]
Feedback timeout.  If you want to revisit this in the future, please reopen.  Thanks!
