### ISSUE TITLE
[Request] Provide alternative instructions for generating a keytab file on Linux

### ISSUE THREAD

**Issue by 3lpsy** [freenas/freenas-docs#1799]
In the docs, there are instructions for generating a keytab file on Windows (https://www.truenas.com/docs/hub/initial-setup/directory-services/kerberos/). I recommend providing an alternative method for generating the keytab file on linux.

**Comment by Mrt134** [comment]
This repository is for the retired Sphinx user guide. You're very welcome to open a pull request with new text in the active documentation repository: https://github.com/freenas/documentation/ ! Alternately, you can open a suggestion ticket in the NAS Jira project: https://jira.ixsystems.com/projects/NAS/issues . Thanks!
