### ISSUE TITLE
[Request] Provide additional troubleshooting documentation for Kerberos

### ISSUE THREAD

**Issue by 3lpsy** [freenas/freenas-docs#1800]
The Active Directory documentation has information regarding troubleshooting. I highly recommend providing similar documentation for Kerberos.

**Comment by Mrt134** [comment]
This repository is for the retired Sphinx user guide. You're very welcome to open a pull request with new text in the active documentation repository: https://github.com/freenas/documentation/ ! Alternately, you can open a suggestion ticket in the NAS Jira project: https://jira.ixsystems.com/projects/NAS/issues . Thanks!
