### ISSUE TITLE
[Request] Provide FreeIPA Integration Guide for NFS and other Shares

### ISSUE THREAD

**Issue by 3lpsy** [freenas/freenas-docs#1801]
FreeIPA is one of the most popular selfhosted authn/authz solutions. I recommend providing a dedicated guide for integrating FreeIPA and Freenas/Truenas.

**Comment by Mrt134** [comment]
This repository is for the retired Sphinx user guide. You're very welcome to open a pull request with new text in the active documentation repository: https://github.com/freenas/documentation/ ! Alternately, you can open a suggestion ticket in the NAS Jira project: https://jira.ixsystems.com/projects/NAS/issues . Thanks!
