### ISSUE TITLE
Link to README for contributing to docs is a 404

### ISSUE THREAD

**Issue by alanwsmith** [freenas/freenas-docs#19]
The [intro](https://doc.freenas.org/9.10/intro.html) for the current docs contains:

> The FreeNAS® User Guide is a work in progress and relies on the contributions of many individuals. If you are interested in helping us to improve the Guide, read the instructions in the README.

With a link that points to:

`https://github.com/freenas/freenas/blob/master/docs/userguide/README.md`

I get a 404 when trying to access that page. It looks like the link should now point to:

`https://github.com/freenas/freenas-docs/blob/master/README.md`

**Comment by wblock** [comment]
Fixed in https://github.com/freenas/freenas-docs/commit/566cc3c5193e1916f1343ccd65dd29b30b552824

Thanks!
